// BuffEffect.h: interface for the CBuffEffect class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_BUFFEFFECT_H__F0F1694E_8F69_4585_A186_C80F6AB2BE61__INCLUDED_)
#define AFX_BUFFEFFECT_H__F0F1694E_8F69_4585_A186_C80F6AB2BE61__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "BuffScriptLoader.h"

typedef OBJECTSTRUCT* LPOBJECTSTRUCT;

enum EFFECTTYPE_DEFINE {
	EFFECTTYPE_NONE = 0x0,
	EFFECTTYPE_INCREASE_ATTACKSPEED = 0x1,
	EFFECTTYPE_INCREASE_DAMAGE = 0x2,
	EFFECTTYPE_INCREASE_DEFENSE = 0x3,
	EFFECTTYPE_INCREASE_LIFE = 0x4,
	EFFECTTYPE_INCREASE_MANA = 0x5,
	EFFECTTYPE_EXPERIENCE = 0x6,
	EFFECTTYPE_ITEMDROPRATE = 0x7,
	EFFECTTYPE_EXPERIENCE_ZERO = 0x8,
	EFFECTTYPE_INCREASE_STRENGTH = 0x9,
	EFFECTTYPE_INCREASE_DEXTERITY = 0xa,
	EFFECTTYPE_INCREASE_VITALITY = 0xb,
	EFFECTTYPE_INCREASE_ENERGY = 0xc,
	EFFECTTYPE_INCREASE_COMMAND = 0xd,
	EFFECTTYPE_INCREASE_PHYSICAL_DAMAGE = 0xe,
	EFFECTTYPE_INCREASE_SPELL_DAMAGE = 0xf,
	EFFECTTYPE_MAPMOVEFREE = 0x10,
	EFFECTTYPE_INCREASE_CRITICAL_DAMAGE = 0x11,
	EFFECTTYPE_DOT_GENERAL = 0x12,
	EFFECTTYPE_DOT_POISON = 0x13,
	EFFECTTYPE_REDUCE_MOVE_SPEED = 0x14,
	EFFECTTYPE_MANA_SHIELD = 0x15,
	EFFECTTYPE_IMPROVE_MAGIC_DEFENSE = 0x16,
	EFFECTTYPE_DECREASE_DEFENSE = 0x17,
	EFFECTTYPE_INCREASE_DAMAGE_REFLECT = 0x18,
	EFFECTTYPE_SLEEP = 0x19,
	EFFECTTYPE_REDUCE_ATTACK_RATE = 0x1a,
	EFFECTTYPE_CURSE_DAMAGE = 0x1b,
	EFFECTTYPE_UNUSED = 0x1c,
	EFFECTTYPE_DECREASE_DAMAGE = 0x1d,
	EFFECTTYPE_DECREASE_DEFENSE_SUM = 0x1e,
	EFFECTTYPE_INCREASE_AMPLIFY_DAMAGE = 0x1f,
	EFFECTTYPE_DECREASE_AMPLIFY_DAMAGE = 0x20,
	EFFECTTYPE_INCREASE_MINIMUM_SPELL_DAMAGE = 0x21,
	EFFECTTYPE_INCREASE_MAXIMUM_SPELL_DAMAGE = 0x22,
	EFFECTTYPE_IMPROVE_DAMAGE_PER = 0x33,
	EFFECTTYPE_ABSORB_DAMAGE = 0x34,
	EFFECTTYPE_RECOVERY_HP = 0x35,
	EFFECTTYPE_RECOVERY_MANA = 0x36,
	EFFECTTYPE_INCREASE_CRITICAL_STRIKE_CHANCE = 0x37,
	EFFECTTYPE_EXCELLENTDAMAGE = 0x38,
	EFFECTTYPE_POWER_UP = 0x39,
	EFFECTTYPE_GUARD_UP = 0x3a,
	EFFECTTYPE_AG_RECOVERY_UP = 0x3b,
	EFFECTTYPE_VULCANUS_EXPERIENCE = 0x3c,
	EFFECTTYPE_VULCANUS_ITEMDROPRATE = 0x3d,
	EFFECTTYPE_GUARD_EXPNITEM = 0x3e,
	EFFECTTYPE_PROTECT_ITEM = 0x3f,
	EFFECTTYPE_ZEN_UP = 0x40,
	EFFECTTYPE_AG_UP = 0x42,
	EFFECTTYPE_SD_UP = 0x43,
	EFFECTTYPE_AG_UP_VALUE = 0x47,
	EFFECTTYPE_SD_UP_VALUE = 0x46,
	EFFECTTYPE_IGNORE_OPPONENT_DEFENSE = 0x48,
	EFFECTTYPE_INCREASE_VITALITY_RF = 0x49,
	EFFECTTYPE_MASTERED_REFLEXES_RESIST = 0x4A,
	EFFECTTYPE_MASTERED_REFLEXES_MAX = 0x4B,
	EFFECTTYPE_MONK_DECREASE_DEFENSE = 0x4C,
	EFFECTTYPE_INCREASE_ALLSTATS = 0x4D,
	EFFECTTYPE_BLIND = 0x4E,
	EFFECTTYPE_DECREASE_ATTACK_SPEED_PERCENT = 0x4F,
	EFFECTTYPE_DOT_VAMPIRIC = 0x50,
	EFFECTTYPE_INCREASE_ATTACK_SPEED_PERCENT = 0x51,
	EFFECTTYPE_ASCENSION_MARK_EXP = 0x57,
	EFFECTTYPE_LIGHT_BLESS_EXP = 0x58,
	EFFECTTYPE_AG_OPPONENT_DECREASE = 0x59,
	EFFECTTYPE_WRATH_INC_DAMAGE = 0x5A,
	EFFECTTYPE_EARTH_DEBUFF = 0x5B,
	EFFECTTYPE_LIGHTNING_DEBUFF = 0x5C,
	EFFECTTYPE_WATER_DEBUFF = 0x5D,
	EFFECTTYPE_DOT_ROT = 0x5E,
	EFFECTTYPE_DOT_IMPROVED_POISON = 0x5F,
	EFFECTTYPE_LIFE_REGENERATION = 0x60,
	EFFECTTYPE_INCREASE_STUN_RESISTANCE = 0x61,
	EFFECTTYPE_LIGHTNING_MASTERY_DEBUFF = 0x62,
	EFFECTTYPE_INCREASE_LETHAL_STRIKE_CHANCE = 0x63,
	EFFECTTYPE_IMPROVED_TOUGHNESS = 0x64
};

struct PMSG_ANS_PERIODBUFF_SELECT {
	PBMSG_HEAD2 h;
	WORD wUserIndex;
	char szCharacterName[MAX_ACCOUNT_LEN+1];
	BYTE btResultCode;
	WORD wBuffIndex;
	BYTE btEffectType1;
	BYTE btEffectType2;
	time_t lExpireDate;
};

class CBuffEffect {
public:
	CBuffEffect();
	virtual ~CBuffEffect();

	void BUFFEFFECT_SetEffect(LPOBJECTSTRUCT lpObj, BYTE EffectType, int EffectValue);
	void BUFFEFFECT_ClearEffect(LPOBJECTSTRUCT lpObj, BYTE EffectType, int EffectValue);
	void BUFFEFFECT_SetDOT(LPOBJECTSTRUCT lpObj, BYTE EffectType, int EffectValue);
	void SetPrevEffect(LPOBJECTSTRUCT lpObj);
	void SetNextEffect(LPOBJECTSTRUCT lpObj);
	void ClearPrevEffect(LPOBJECTSTRUCT lpObj);
	void BUFFEFFECT_DamageOverTime(LPOBJECTSTRUCT lpObj, int Damage);
	void BUFFEFFECT_Poison(LPOBJECTSTRUCT lpObj, BYTE PoisonRate);
	void BUFFEFFECT_ImprovedPoison(LPOBJECTSTRUCT lpObj, BYTE PoisonRate);
	void BUFFEFFECT_Rot(LPOBJECTSTRUCT lpObj, int PoisonRate);
	void BUFFEFFECT_Vampiric(LPOBJECTSTRUCT lpObj, int Damage);
	void RequestGuildPeriodBuffInsert(char *szGuildName, _tagPeriodBuffInfo *lpBuffInfo);
	void RequestGuildPeriodBuffDelete(WORD *wBuffIndex, char btGuildCnt);
	void RequestPeriodBuffDelete(OBJECTSTRUCT *lpObj, WORD wBuffIndex);
	void RequestPeriodBuffDelete(char *szName, WORD wBuffIndex);
	void RequestPeriodBuffInsert(OBJECTSTRUCT *lpObj, _tagPeriodBuffInfo *lpBuffInfo);
	void RequestPeriodBuffSelect(OBJECTSTRUCT *lpObj);
	void DGPeriodItemExSelect(PMSG_ANS_PERIODBUFF_SELECT *lpMsg);
};

extern CBuffEffect	g_BuffEffect;

#endif